### ISSUE TITLE
Sleek Chat conflict with notebook module

### ISSUE THREAD

**Issue by jacksands** [mordachai/sleek-chat#4]
Hello!  tks for the cool module!

I just tested it, and found it has a conflict with notebook, probably because it creates a new tab on the side bar.

notebook git.
https://github.com/Saibot393/notebook

https://github.com/user-attachments/assets/729686ac-6de9-450a-9ddd-f56675764a6a

notebook is quite useful, it would be cool to use then both!

in any case tks once again!

**Comment by mordachai** [comment]
I didn't know this module, but it seems useful. I will try to work on something!

**Comment by jacksands** [comment]
https://github.com/bmarian/chat-images

another module with conflict, if you can take a look!

If you can please!!!

**Comment by leonkennedy6** [comment]
Works for me with [Chat Media](https://foundryvtt.com/packages/chat-media), which you should be using anyway since the old one is no longer being maintained.

**Comment by jacksands** [comment]
I didn't know!  tks!

**Comment by gus-uktena** [comment]
Solved and also added option for sound notification, check the settings
Thanks everyone!

**Comment by mordachai** [comment]
Solved. And added option for sound notification, check in the settings
